spring:
  application:
    name: kafka-streams-boilerplate

  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.11.70.2:29092,172.11.70.2:29093,172.11.70.2:29094
          configuration:
            commit.interval.ms: 1000
      bindings:
        processStreams-in-0:
          destination: input-topic
          content-type: application/json
        processStreams-out-0:
          destination: output-topic
          content-type: application/json
  kafka:
    bootstrap-servers: 172.11.70.2:29092,172.11.70.2:29093,172.11.70.2:29094
    streams:
      application-id: kafka-streams-app
      bootstrap-servers: 172.11.70.2:29092,172.11.70.2:29093,172.11.70.2:29094
#      default:
#        key-serializer: org.apache.kafka.common.serialization.Serdes$StringSerde
#        key-deserializer: org.apache.kafka.common.serialization.Serdes$StringSerde
#        value-serializer: org.apache.kafka.common.serialization.Serdes$StringSerde
#        value-deserializer: org.apache.kafka.common.serialization.Serdes$StringSerde
      state-dir: ./tmp/kafka-streams
